[package]
name = "tobydavis-dev"
version = "0.1.0"
authors = ["Toby Davis"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
comrak = "0.51.0"
dioxus = { version = "0.7.4", features = ["router", "fullstack"] }
serde = { version = "1", features = ["derive"] }
toml = "1.1.2"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = ["dioxus/server"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true
debug = false
debug-assertions = false
