[package]
name = "tobydavis-dev"
version = "0.1.0"
authors = ["Toby Davis"]
edition = "2024"

[dependencies]
dioxus = { version = "=0.7.7", features = ["router", "fullstack"] }
wasm-bindgen = "=0.2.120"

typst = { version = "0.14", optional = true }
typst-assets = { version = "0.14", features = ["fonts"], optional = true }
typst-html = { version = "0.14", optional = true }
typst-kit = { version = "0.14", optional = true }
moka = { version = "0.12", features = ["sync"], optional = true }

chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
toml = "1.1.2"

getrandom = { version = "*", features = ["wasm_js"] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = ["dioxus/server", "typst", "typst-assets", "typst-html", "typst-kit", "moka"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true
debug = false
debug-assertions = false
